# Generated by Django 5.2.7 on 2025-10-31 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('d', 'Dark'), ('l', 'Light')], default='d')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'Deutsch'), ('es', 'Español'), ('it', 'Italiano'), ('pt', 'Português'), ('ru', 'Русский'), ('ja', '日本語'), ('zh', '中文'), ('ar', 'العربية'), ('hi', 'हिंदी')], default='en')),
                ('email_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to='profiles.profile')),
            ],
        ),
    ]
